docker4
Otus-DevOps-22-08/AleksandrKucepalov_microservices pull request #3
Opened 2022-12-27 10:12 UTC by AleksandrKucepalov

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
В процессе сделано:
Разобрались с работой сети в Docker
Установили docker-compose на локальную машину
Собрали образы приложения reddit с помощью docker-compose
Запустили приложение reddit с помощью docker-compose

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-12-27 18:25 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужны небольшие правки
Комментарий к тому что надо поправить оставил =)

2022-12-27 18:25 UTC, mrgreyves commented on src/.env.example
> +USERNAME = your_login
Пробелов быть не должно
Можно посмотреть в документации как оно выглядит
https://docs.docker.com/compose/environment-variables/

2022-12-28 08:14 UTC, AleksandrKucepalov commented on src/.env.example
> +USERNAME = your_login
Добрый день.
Про пробелы спасибо, поправил. 
Тестовый пытался сделать красивее) 
Не могу понять что не так....
Почему тест не проходит.

2023-01-07 08:36 UTC, mrgreyves approved these changes
Здравствуйте!)
Перед мержем проверьте еще раз почему не собирается образ =)

2023-01-08 07:32 UTC, merged